// 资源数据
const resourcesData = [
    {
        id: 1,
        name: "Johnathan Bi",
        level: "Advanced",
        levelZh: "高级",
        category: "Videos",
        categoryZh: "视频",
        type: "listening",
        tags: ["Philosophy", "Books", "Lecture"],
        tagsZh: ["哲学", "书籍", "讲座"],
        description: "Philosophy lectures and book discussions by Johnathan Bi, exploring deep intellectual topics.",
        descriptionZh: "Johnathan Bi的哲学讲座和书籍讨论，探索深刻的学术话题。",
        shortDescription: "Philosophy lectures and book discussions by Johnathan Bi.",
        shortDescriptionZh: "Johnathan Bi的哲学讲座和书籍讨论。",
        detailedDescription: "Philosophy lectures and book discussions by Johnathan Bi, exploring deep intellectual topics. Ideal for advanced learners interested in complex philosophical concepts and in-depth analyses of various books.",
        detailedDescriptionZh: "Johnathan Bi的哲学讲座和书籍讨论，探索深刻的学术话题。非常适合对复杂哲学概念和书籍深入分析感兴趣的高级学习者。",
        link: "https://www.youtube.com/@bi.johnathan",
        image: "public/Jonathan.png",
        emoji: "📚"
    },
    {
        id: 2,
        name: "Jay Shetty Podcast",
        level: "Upper-Intermediate",
        levelZh: "中上级",
        category: "Videos/Podcasts",
        categoryZh: "视频/播客",
        type: "listening",
        tags: ["Health", "Personal Development", "Interview"],
        tagsZh: ["健康", "个人成长", "访谈"],
        description: "Inspiring conversations about health, wellness, and personal growth.",
        descriptionZh: "关于健康、幸福和个人成长的启发式对话。",
        shortDescription: "Inspiring conversations about health, wellness, and personal growth.",
        shortDescriptionZh: "关于健康、幸福和个人成长的启发式对话。",
        detailedDescription: "Inspiring conversations about health, wellness, and personal growth with various guests. Jay Shetty shares wisdom and practical advice for a meaningful life, suitable for those seeking personal development.",
        detailedDescriptionZh: "与各界嘉宾进行关于健康、幸福和个人成长的启发式对话。Jay Shetty分享智慧和实用建议，助你过上更有意义的生活，适合寻求个人成长的人士。",
        link: "https://www.youtube.com/@JayShettyPodcast.",
        image: "public/Jay Shetty.jpeg",
        emoji: "🧘"
    },
    {
        id: 3,
        name: "The Diary of a CEO",
        level: "Upper-Intermediate",
        levelZh: "中上级",
        category: "Videos/Podcasts",
        categoryZh: "视频/播客",
        type: "listening",
        tags: ["Multiple Topics", "Interview"],
        tagsZh: ["多主题", "访谈"],
        description: "Honest conversations with successful entrepreneurs and leaders.",
        descriptionZh: "与成功企业家和领导者的真诚对话。",
        shortDescription: "Honest conversations with successful entrepreneurs and leaders.",
        shortDescriptionZh: "与成功企业家和领导者的真诚对话。",
        detailedDescription: "The Diary of a CEO features honest conversations with some of the world's most influential people, including entrepreneurs, leaders, and artists. Stephen Bartlett explores their journeys, challenges, and insights.",
        detailedDescriptionZh: "《CEO日记》呈现了与世界上最具影响力人物的真诚对话，包括企业家、领导者和艺术家。Stephen Bartlett深入探讨他们的旅程、挑战和见解。",
        link: "https://www.youtube.com/@TheDiaryOfACEO",
        image: "public/DOAC.png",
        emoji: "🎙️"
    },
    {
        id: 4,
        name: "Huberman Lab",
        level: "Upper-Intermediate",
        levelZh: "中上级",
        category: "Videos/Podcasts",
        categoryZh: "视频/播客",
        type: "listening",
        tags: ["Health", "Monologue", "Interview"],
        tagsZh: ["健康", "独白", "访谈"],
        description: "Science-based discussions about neuroscience and health optimization.",
        descriptionZh: "基于科学的神经科学和健康优化讨论。",
        shortDescription: "Science-based discussions about neuroscience and health optimization.",
        shortDescriptionZh: "基于科学的神经科学和健康优化讨论。",
        detailedDescription: "Dr. Andrew Huberman, a neuroscientist, discusses neuroscience and tools for optimizing brain and body function. His episodes cover various topics from sleep to focus, presented in an accessible scientific manner.",
        detailedDescriptionZh: "神经科学家Andrew Huberman博士讨论神经科学以及优化大脑和身体功能的工具。他的节目涵盖从睡眠到专注的各种话题，以易于理解的科学方式呈现。",
        link: "https://www.youtube.com/@hubermanlab/videos",
        image: "public/Huberman.png",
        emoji: "🧠"
    },
    {
        id: 5,
        name: "Ali Abdaal",
        level: "Upper-Intermediate",
        levelZh: "中上级",
        category: "Videos",
        categoryZh: "视频",
        type: "listening",
        tags: ["Productivity", "Personal Development"],
        tagsZh: ["生产力", "个人发展"],
        description: "Productivity tips, study techniques, and personal development content.",
        descriptionZh: "生产力技巧、学习方法和个人发展内容。",
        shortDescription: "Productivity tips, study techniques, and personal development content.",
        shortDescriptionZh: "生产力技巧、学习方法和个人发展内容。",
        detailedDescription: "Ali Abdaal, a doctor turned YouTuber, shares insights on productivity, study techniques, and personal development. His content is popular among students and young professionals looking to maximize their potential.",
        detailedDescriptionZh: "Ali Abdaal，一位医生出身的YouTuber，分享关于生产力、学习方法和个人发展的见解。他的内容在学生和寻求最大化潜力的年轻专业人士中很受欢迎。",
        link: "https://www.youtube.com/@aliabdaal",
        image: "public/Ali.jpeg",
        emoji: "💼"
    },
    {
        id: 6,
        name: "TED Talks",
        level: "Upper-Intermediate",
        levelZh: "中上级",
        category: "Videos",
        categoryZh: "视频",
        type: "listening",
        tags: ["Multiple Topics", "Inspiration"],
        tagsZh: ["多主题", "励志"],
        description: "Ideas worth spreading - inspiring talks on various topics.",
        descriptionZh: "值得传播的思想 - 关于各种主题的启发式演讲。",
        shortDescription: "Ideas worth spreading - inspiring talks on various topics.",
        shortDescriptionZh: "值得传播的思想 - 关于各种主题的启发式演讲。",
        detailedDescription: "TED Talks feature leading thinkers and doers from around the world sharing their ideas on technology, entertainment, design, science, business, and global issues. These talks aim to spark curiosity and inspire change.",
        detailedDescriptionZh: "TED演讲汇集了来自世界各地的顶尖思想家和实践者，分享他们在科技、娱乐、设计、科学、商业和全球问题方面的见解。这些演讲旨在激发好奇心并促进行动。",
        link: "https://www.ted.com/talks",
        image: "public/TED.png",
        emoji: "💡"
    },
    {
        id: 7,
        name: "CNN 10",
        level: "Upper-Intermediate",
        levelZh: "中上级",
        category: "Videos",
        categoryZh: "视频",
        type: "listening",
        tags: ["Global News"],
        tagsZh: ["全球新闻"],
        description: "Daily news program designed for students, covering global events.",
        descriptionZh: "专为学生设计的每日新闻节目，涵盖全球事件。",
        shortDescription: "Daily news program designed for students, covering global events.",
        shortDescriptionZh: "专为学生设计的每日新闻节目，涵盖全球事件。",
        detailedDescription: "CNN 10 is a daily news program tailored for students, offering a clear and concise summary of global events. It's an excellent resource for staying informed and improving English listening comprehension.",
        detailedDescriptionZh: "CNN 10是一个专为学生设计的每日新闻节目，提供全球事件的清晰简洁摘要。它是保持信息灵通和提高英语听力理解能力的绝佳资源。",
        link: "https://edition.cnn.com/cnn10",
        image: "public/CNN10.jpg",
        emoji: "📺"
    },
    {
        id: 8,
        name: "The Psychology of Your 20s",
        level: "Intermediate",
        levelZh: "中级",
        category: "Videos/Podcasts",
        categoryZh: "视频/播客",
        type: "listening",
        tags: ["Psychology", "Wellbeing"],
        tagsZh: ["心理学", "健康"],
        description: "Exploring psychological topics relevant to young adults.",
        descriptionZh: "探索与年轻人相关的心理学话题。",
        shortDescription: "Exploring psychological topics relevant to young adults.",
        shortDescriptionZh: "探索与年轻人相关的心理学话题。",
        detailedDescription: "This podcast delves into psychological topics that are particularly relevant to young adults navigating their 20s. It offers insights into relationships, career, mental health, and personal growth.",
        detailedDescriptionZh: "这个播客深入探讨与年轻人在20多岁时特别相关的心理学话题。它提供了关于人际关系、职业、心理健康和个人成长的见解。",
        link: "https://www.youtube.com/@thepsychologyofyour20s/videos",
        image: "public/psychology of 20s.jpg",
        emoji: "🧠"
    },
    {
        id: 9,
        name: "Professor Dave Explains",
        level: "Intermediate",
        levelZh: "中级",
        category: "Videos",
        categoryZh: "视频",
        type: "listening",
        tags: ["Multiple Topics", "Science"],
        tagsZh: ["多主题", "科学"],
        description: "Educational videos explaining various scientific concepts.",
        descriptionZh: "解释各种科学概念的教育视频。",
        shortDescription: "Educational videos explaining various scientific concepts.",
        shortDescriptionZh: "解释各种科学概念的教育视频。",
        detailedDescription: "Professor Dave Explains offers clear and concise educational videos on a wide range of scientific subjects, including chemistry, physics, biology, and more. Perfect for students and curious minds.",
        detailedDescriptionZh: "Professor Dave Explains提供关于广泛科学科目（包括化学、物理、生物等）的清晰简洁的教育视频。非常适合学生和好奇的人。",
        link: "https://www.youtube.com/@ProfessorDaveExplains",
        image: "public/professor dave explains.png",
        emoji: "🧪"
    },
    {
        id: 10,
        name: "EnglishPod",
        level: "Lower-Intermediate",
        levelZh: "中下级",
        category: "Podcasts",
        categoryZh: "播客",
        type: "listening",
        tags: ["Everyday Conversation"],
        tagsZh: ["日常对话"],
        description: "English learning podcast focusing on everyday conversations.",
        descriptionZh: "专注于日常对话的英语学习播客。",
        shortDescription: "English learning podcast focusing on everyday conversations.",
        shortDescriptionZh: "专注于日常对话的英语学习播客。",
        detailedDescription: "EnglishPod offers practical English lessons centered around everyday conversations. Each episode covers common scenarios, vocabulary, and phrases, ideal for improving conversational English.",
        detailedDescriptionZh: "EnglishPod提供以日常对话为中心的实用英语课程。每集涵盖常见场景、词汇和短语，是提高英语口语的理想选择。",
        link: "https://www.bilibili.com/video/BV1w7411g7jn/?spm_id_from=333.337.search-card.all.click&vd_source=9fdd2a15e6b7853784d969e63c68f6de",
        image: "public/Englishpod.png",
        emoji: "🎧"
    },
    {
        id: 11,
        name: "Magic Tree House",
        level: "Lower-Intermediate",
        levelZh: "中下级",
        category: "Audiobooks/Books",
        categoryZh: "有声书/书籍",
        type: "reading",
        tags: ["Kids", "Stories"],
        tagsZh: ["儿童", "故事"],
        description: "Adventure stories for children, great for English learners.",
        descriptionZh: "适合儿童的冒险故事，非常适合英语学习者。",
        shortDescription: "Adventure stories for children, great for English learners.",
        shortDescriptionZh: "适合儿童的冒险故事，非常适合英语学习者。",
        detailedDescription: "The Magic Tree House series features Jack and Annie's magical adventures through time. These engaging stories are perfect for young English learners to build vocabulary and reading comprehension in a fun way.",
        detailedDescriptionZh: "《神奇树屋》系列讲述了Jack和Annie穿越时空的奇妙冒险。这些引人入胜的故事非常适合年轻的英语学习者，以有趣的方式积累词汇和提高阅读理解能力。",
        link: "https://www.bilibili.com/video/BV1Zv411Ux76/?spm_id_from=333.337.search-card.all.click&vd_source=9fdd2a15e6b7853784d969e63c68f6de",
        image: "public/Magic.webp",
        emoji: "📖"
    },
    {
        id: 12,
        name: "BBC 6 Minute English",
        level: "Lower-Intermediate",
        levelZh: "中下级",
        category: "Podcasts",
        categoryZh: "播客",
        type: "listening",
        tags: ["Multiple Topics", "Global News"],
        tagsZh: ["多主题", "全球新闻"],
        description: "Short English lessons covering interesting topics and current events.",
        descriptionZh: "涵盖有趣话题和时事新闻的简短英语课程。",
        shortDescription: "Short English lessons covering interesting topics and current events.",
        shortDescriptionZh: "涵盖有趣话题和时事新闻的简短英语课程。",
        detailedDescription: "BBC 6 Minute English offers short, engaging English lessons on a variety of interesting topics and current events. Each episode includes vocabulary, transcripts, and quizzes, making it ideal for intermediate learners.",
        detailedDescriptionZh: "BBC 6分钟英语提供关于各种有趣话题和时事新闻的简短而引人入胜的英语课程。每集包括词汇、文本和测验，非常适合中级学习者。",
        link: "https://www.bbc.co.uk/learningenglish/english/features/6-minute-english",
        image: "public/BBC.png",
        emoji: "🌍"
    },
    {
        id: 13,
        name: "美国中小学课程-外教精讲",
        level: "Elementary",
        levelZh: "初级",
        category: "Videos",
        categoryZh: "视频",
        type: "listening",
        tags: ["Multiple Topics"],
        tagsZh: ["多主题"],
        description: "Elementary school curriculum taught by native English teachers.",
        descriptionZh: "由英语母语教师教授的小学课程。",
        shortDescription: "Elementary school curriculum taught by native English teachers.",
        shortDescriptionZh: "由英语母语教师教授的小学课程。",
        detailedDescription: "This series covers elementary school curriculum taught by native English teachers, making complex topics accessible for young learners. It's a great way for beginners to build foundational English skills.",
        detailedDescriptionZh: "本系列涵盖由英语母语教师教授的小学课程，使复杂的 topic 对年轻学习者来说易于理解。对于初学者来说，这是建立英语基础技能的好方法。",
        link: "https://www.bilibili.com/video/BV1f6uJzFEIV/?spm_id_from=333.1387.search.video_card.click&vd_source=9fdd2a15e6b7853784d969e63c68f6de",
        emoji: "🎓"
    }
];

