// 资源数据
const resourcesData = [
    {
        id: 1,
        name: "Johnathan Bi",
        level: "Advanced",
        levelZh: "高级",
        category: "Videos",
        categoryZh: "视频",
        type: "listening",
        tags: ["Philosophy", "Books", "Lecture"],
        tagsZh: ["哲学", "书籍", "讲座"],
        shortDescription: "Philosophy lectures and book discussions by Johnathan Bi.",
        shortDescriptionZh: "Johnathan Bi的哲学讲座和书籍讨论。",
        detailedDescription: "Philosophy lectures and book discussions by Johnathan Bi, exploring deep intellectual topics. Ideal for advanced learners interested in complex philosophical concepts and in-depth analyses of various books.",
        detailedDescriptionZh: "Johnathan Bi的哲学讲座和书籍讨论，探索深刻的学术话题。非常适合对复杂哲学概念和书籍深入分析感兴趣的高级学习者。",
        youtubeLink: "https://www.youtube.com/@bi.johnathan",
        youtubeLinkName: "Visit on YouTube",
        youtubeLinkNameZh: "在 YouTube 上访问",
        alternateLink: "https://space.bilibili.com/3546799388232614/",
        alternateLinkName: "Visit on Bilibili",
        alternateLinkNameZh: "在 Bilibili 上访问",
        image: "public/Jonathan.png",
        emoji: "📚"
    },
    {
        id: 2,
        name: "Jay Shetty Podcast",
        level: "Upper-Intermediate",
        levelZh: "中上级",
        category: "Videos/Podcasts",
        categoryZh: "视频/播客",
        type: "listening",
        tags: ["Health", "Personal Development", "Interview"],
        tagsZh: ["健康", "个人成长", "访谈"],
        shortDescription: "Inspiring conversations about health, wellness, and personal growth.",
        shortDescriptionZh: "关于健康、幸福和个人成长的启发式对话。",
        detailedDescription: "Inspiring conversations about health, wellness, and personal growth with various guests. Jay Shetty shares wisdom and practical advice for a meaningful life, suitable for those seeking personal development.",
        detailedDescriptionZh: "与各界嘉宾进行关于健康、幸福和个人成长的启发式对话。Jay Shetty分享智慧和实用建议，助你过上更有意义的生活，适合寻求个人成长的人士。",
        youtubeLink: "https://www.youtube.com/@JayShettyPodcast.",
        youtubeLinkName: "Visit on YouTube",
        youtubeLinkNameZh: "在 YouTube 上访问",
        alternateLink: "https://podcasts.apple.com/cn/podcast/on-purpose-with-jay-shetty/id1450994021",
        alternateLinkName: "Visit on Apple Podcasts",
        alternateLinkNameZh: "在苹果播客上访问",
        image: "public/Jay Shetty.jpeg",
        emoji: "🧘"
    },
    {
        id: 3,
        name: "The Diary of a CEO",
        level: "Upper-Intermediate",
        levelZh: "中上级",
        category: "Videos/Podcasts",
        categoryZh: "视频/播客",
        type: "listening",
        tags: ["Multiple Topics", "Interview"],
        tagsZh: ["多主题", "访谈"],
        shortDescription: "Honest conversations with successful entrepreneurs and leaders.",
        shortDescriptionZh: "与成功企业家和领导者的真诚对话。",
        detailedDescription: "The Diary of a CEO features honest conversations with some of the world's most influential people, including entrepreneurs, leaders, and artists. Stephen Bartlett explores their journeys, challenges, and insights.",
        detailedDescriptionZh: "《CEO日记》呈现了与世界上最具影响力人物的真诚对话，包括企业家、领导者和艺术家。Stephen Bartlett深入探讨他们的旅程、挑战和见解。",
        youtubeLink: "https://www.youtube.com/@TheDiaryOfACEO",
        youtubeLinkName: "Visit on YouTube",
        youtubeLinkNameZh: "在 YouTube 上访问",
        alternateLink: "https://podcasts.apple.com/cn/podcast/the-diary-of-a-ceo-with-steven-bartlett/id1291423644",
        alternateLinkName: "Visit on Apple Podcasts",
        alternateLinkNameZh: "在苹果播客上访问",
        image: "public/DOAC.png",
        emoji: "🎙️"
    },
    {
        id: 4,
        name: "Huberman Lab",
        level: "Upper-Intermediate",
        levelZh: "中上级",
        category: "Videos/Podcasts",
        categoryZh: "视频/播客",
        type: "listening",
        tags: ["Health", "Monologue", "Interview"],
        tagsZh: ["健康", "独白", "访谈"],
        shortDescription: "Science-based discussions about neuroscience and health optimization.",
        shortDescriptionZh: "基于科学的神经科学和健康优化讨论。",
        detailedDescription: "Dr. Andrew Huberman, a neuroscientist, discusses neuroscience and tools for optimizing brain and body function. His episodes cover various topics from sleep to focus, presented in an accessible scientific manner.",
        detailedDescriptionZh: "神经科学家Andrew Huberman博士讨论神经科学以及优化大脑和身体功能的工具。他的节目涵盖从睡眠到专注的各种话题，以易于理解的科学方式呈现。",
        youtubeLink: "https://www.youtube.com/@hubermanlab/videos",
        youtubeLinkName: "Visit on YouTube",
        youtubeLinkNameZh: "在YouTube上访问",
        alternateLink: "https://podcasts.apple.com/cn/podcast/huberman-lab/id1545953110",
        alternateLinkName: "Visit on Apple Podcasts",
        alternateLinkNameZh: "在苹果播客上访问",
        image: "public/Huberman.png",
        emoji: "🧠"
    },
    {
        id: 5,
        name: "Ali Abdaal",
        level: "Upper-Intermediate",
        levelZh: "中上级",
        category: "Videos",
        categoryZh: "视频",
        type: "listening",
        tags: ["Productivity", "Personal Development"],
        tagsZh: ["生产力", "个人发展"],
        shortDescription: "Productivity tips, study techniques, and personal development content.",
        shortDescriptionZh: "生产力技巧、学习方法和个人发展内容。",
        detailedDescription: "Ali Abdaal, a doctor turned YouTuber, shares insights on productivity, study techniques, and personal development. His content is popular among students and young professionals looking to maximize their potential.",
        detailedDescriptionZh: "Ali Abdaal，一位医生出身的YouTuber，分享关于生产力、学习方法和个人发展的见解。他的内容在学生和寻求最大化潜力的年轻专业人士中很受欢迎。",
        youtubeLink: "https://www.youtube.com/@aliabdaal",
        youtubeLinkName: "Visit on YouTube",
        youtubeLinkNameZh: "在YouTube上访问",
        alternateLink: "https://space.bilibili.com/3546581580122806",
        alternateLinkName: "Visit on Bilibili",
        alternateLinkNameZh: "在Bilibili上访问",
        image: "public/Ali.jpeg",
        emoji: "💼"
    },
    {
        id: 6,
        name: "TED Talks",
        level: "Upper-Intermediate",
        levelZh: "中上级",
        category: "Videos",
        categoryZh: "视频",
        type: "listening",
        tags: ["Multiple Topics", "Inspiration"],
        tagsZh: ["多主题", "励志"],
        shortDescription: "Ideas worth spreading - inspiring talks on various topics.",
        shortDescriptionZh: "值得传播的思想 - 关于各种主题的启发式演讲。",
        detailedDescription: "TED Talks feature leading thinkers and doers from around the world sharing their ideas on technology, entertainment, design, science, business, and global issues. These talks aim to spark curiosity and inspire change.",
        detailedDescriptionZh: "TED演讲汇集了来自世界各地的顶尖思想家和实践者，分享他们在科技、娱乐、设计、科学、商业和全球问题方面的见解。这些演讲旨在激发好奇心并促进行动。",
        youtubeLink: "https://www.ted.com/talks",
        youtubeLinkName: "Visit on Official Website",
        youtubeLinkNameZh: "在官方网站上访问",
        alternateLink: "https://www.youtube.com/ted",
        alternateLinkName: "Visit on YouTube",
        alternateLinkNameZh: "在YouTube上访问",
        image: "public/TED.png",
        emoji: "💡"
    },
    {
        id: 7,
        name: "CNN 10",
        level: "Upper-Intermediate",
        levelZh: "中上级",
        category: "Videos",
        categoryZh: "视频",
        type: "listening",
        tags: ["Global News"],
        tagsZh: ["全球新闻"],
        shortDescription: "Daily news program designed for students, covering global events.",
        shortDescriptionZh: "专为学生设计的每日新闻节目，涵盖全球事件。",
        detailedDescription: "CNN 10 is a daily news program tailored for students, offering a clear and concise summary of global events. It's an excellent resource for staying informed and improving English listening comprehension.",
        detailedDescriptionZh: "CNN 10是一个专为学生设计的每日新闻节目，提供全球事件的清晰简洁摘要。它是保持信息灵通和提高英语听力理解能力的绝佳资源。",
        youtubeLink: "https://edition.cnn.com/cnn10",
        youtubeLinkName: "Visit on Official Website",
        youtubeLinkNameZh: "在官方网站上访问",
        alternateLink: "https://www.youtube.com/@CNN10",
        alternateLinkName: "Visit on YouTube",
        alternateLinkNameZh: "在YouTube上访问",
        image: "public/CNN10.jpg",
        emoji: "📰"
    },
    {
        id: 8,
        name: "The Psychology of Your 20s",
        level: "Intermediate",
        levelZh: "中级",
        category: "Videos/Podcasts",
        categoryZh: "视频/播客",
        type: "listening",
        tags: ["Psychology", "Wellbeing"],
        tagsZh: ["心理学", "健康"],
        shortDescription: "Exploring psychological topics relevant to young adults.",
        shortDescriptionZh: "探索与年轻人相关的心理学话题。",
        detailedDescription: "This podcast delves into psychological topics that are particularly relevant to young adults navigating their 20s. It offers insights into relationships, career, mental health, and personal growth.",
        detailedDescriptionZh: "这个播客深入探讨与年轻人在20多岁时特别相关的心理学话题。它提供了关于人际关系、职业、心理健康和个人成长的见解。",
        youtubeLink: "https://www.youtube.com/@thepsychologyofyour20s/videos",
        youtubeLinkName: "Visit on YouTube",
        youtubeLinkNameZh: "在YouTube上访问",
        alternateLink: "https://podcasts.apple.com/cn/podcast/the-psychology-of-your-20s/id1573710078",
        alternateLinkName: "Visit on Apple Podcasts",
        alternateLinkNameZh: "在苹果播客上访问",
        image: "public/psychology of 20s.jpg",
        emoji: "🧠"
    },
    {
        id: 9,
        name: "Professor Dave Explains",
        level: "Intermediate",
        levelZh: "中级",
        category: "Videos",
        categoryZh: "视频",
        type: "listening",
        tags: ["Multiple Topics", "Science"],
        tagsZh: ["多主题", "科学"],
        shortDescription: "Educational videos explaining various scientific concepts.",
        shortDescriptionZh: "解释各种科学概念的教育视频。",
        detailedDescription: "Professor Dave Explains offers clear and concise educational videos on a wide range of scientific subjects, including chemistry, physics, biology, and more. Perfect for students and curious minds.",
        detailedDescriptionZh: "Professor Dave Explains提供关于广泛科学科目（包括化学、物理、生物等）的清晰简洁的教育视频。非常适合学生和好奇的人。",
        youtubeLink: "https://www.youtube.com/@ProfessorDaveExplains",
        youtubeLinkName: "Visit on YouTube",
        youtubeLinkNameZh: "在YouTube上访问",
        alternateLink: "",
        alternateLinkName: "Apple Podcasts",
        alternateLinkNameZh: "Apple Podcasts",
        image: "public/professor dave explains.png",
        emoji: "🧪"
    },
    {
        id: 10,
        name: "EnglishPod",
        level: "Lower-Intermediate",
        levelZh: "中下级",
        category: "Podcasts",
        categoryZh: "播客",
        type: "listening",
        tags: ["Everyday Conversation"],
        tagsZh: ["日常对话"],
        shortDescription: "English learning podcast focusing on everyday conversations.",
        shortDescriptionZh: "专注于日常对话的英语学习播客。",
        detailedDescription: "EnglishPod offers practical English lessons centered around everyday conversations. Each episode covers common scenarios, vocabulary, and phrases, ideal for improving conversational English.",
        detailedDescriptionZh: "EnglishPod提供以日常对话为中心的实用英语课程。每集涵盖常见场景、词汇和短语，是提高英语口语的理想选择。",
        youtubeLink: "https://www.bilibili.com/video/BV1w7411g7jn/?spm_id_from=333.337.search-card.all.click&vd_source=9fdd2a15e6b7853784d969e63c68f6de",
        youtubeLinkName: "Visit on Bilibili",
        youtubeLinkNameZh: "在Bilibili上访问",
        alternateLink: "",
        alternateLinkName: "Apple Podcasts",
        alternateLinkNameZh: "Apple Podcasts",
        image: "public/Englishpod.png",
        emoji: "🎧"
    },
    {
        id: 11,
        name: "Magic Tree House",
        level: "Lower-Intermediate",
        levelZh: "中下级",
        category: "Audiobooks/Books",
        categoryZh: "有声书/书籍",
        type: "reading",
        tags: ["Kids", "Stories"],
        tagsZh: ["儿童", "故事"],
        shortDescription: "Adventure stories for children, great for English learners.",
        shortDescriptionZh: "适合儿童的冒险故事，非常适合英语学习者。",
        detailedDescription: "The Magic Tree House series features Jack and Annie's magical adventures through time. These engaging stories are perfect for young English learners to build vocabulary and reading comprehension in a fun way.",
        detailedDescriptionZh: "《神奇树屋》系列讲述了Jack和Annie穿越时空的奇妙冒险。这些引人入胜的故事非常适合年轻的英语学习者，以有趣的方式积累词汇和提高阅读理解能力。",
        youtubeLink: "https://www.youtube.com/watch?v=wqY2CuBRytk",
        youtubeLinkName: "Visit on YouTube",
        youtubeLinkNameZh: "在YouTube上访问",
        alternateLink: "",
        alternateLinkName: "Visit on Bilibili",
        alternateLinkNameZh: "在Bilibili上访问",
        image: "public/Magic.webp",
        emoji: "📖"
    },
    {
        id: 12,
        name: "BBC 6 Minute English",
        level: "Lower-Intermediate",
        levelZh: "中下级",
        category: "Podcasts",
        categoryZh: "播客",
        type: "listening",
        tags: ["Multiple Topics", "Global News"],
        tagsZh: ["多主题", "全球新闻"],
        shortDescription: "Short English lessons covering interesting topics and current events.",
        shortDescriptionZh: "涵盖有趣话题和时事新闻的简短英语课程。",
        detailedDescription: "BBC 6 Minute English offers short, engaging English lessons on a variety of interesting topics and current events. Each episode includes vocabulary, transcripts, and quizzes, making it ideal for intermediate learners.",
        detailedDescriptionZh: "BBC 6分钟英语提供关于各种有趣话题和时事新闻的简短而引人入胜的英语课程。每集包括词汇、文本和测验，非常适合中级学习者。",
        youtubeLink: "https://www.bbc.co.uk/learningenglish/english/features/6-minute-english",
        youtubeLinkName: "Visit on Official Website",
        youtubeLinkNameZh: "在官方网站上访问",
        alternateLink: "https://www.youtube.com/@bbclearningenglish",
        alternateLinkName: "Visit on YouTube",
        alternateLinkNameZh: "在YouTube上访问",
        image: "public/BBC.png",
        emoji: "🌍"
    },
    {
        id: 13,
        name: "美国中小学课程-外教精讲",
        level: "Elementary",
        levelZh: "初级",
        category: "Videos",
        categoryZh: "视频",
        type: "listening",
        tags: ["Multiple Topics"],
        tagsZh: ["多主题"],
        shortDescription: "Elementary school curriculum taught by native English teachers.",
        shortDescriptionZh: "由英语母语教师教授的小学课程。",
        detailedDescription: "This series covers elementary school curriculum taught by native English teachers, making complex topics accessible for young learners. It's a great way for beginners to build foundational English skills.",
        detailedDescriptionZh: "本系列涵盖由英语母语教师教授的小学课程，使复杂的 topic 对年轻学习者来说易于理解。对于初学者来说，这是建立英语基础技能的好方法。",
        youtubeLink: "https://www.bilibili.com/video/BV1c7411Z78e/?spm_id_from=333.337.search-card.all.click",
        youtubeLinkName: "Visit on Bilibili",
        youtubeLinkNameZh: "在Bilibili上访问",
        alternateLink: "",
        alternateLinkName: "Visit on YouTube",
        alternateLinkNameZh: "在YouTube上访问",
        image: "public/美国中小学课程.jpg",
        emoji: "🧑‍🏫"
    },
    {
        id: 14,
        name: "The Joe Rogan Experience",
        level: "Advanced",
        levelZh: "高级",
        category: "Videos/Podcasts",
        categoryZh: "视频/播客",
        type: "listening",
        tags: ["Multiple Topics", "Interview", "Conversation"],
        tagsZh: ["多主题", "访谈", "对话"],
        shortDescription: "Long-form conversations with fascinating guests on diverse topics.",
        shortDescriptionZh: "与各领域嘉宾进行深入的长对话，涵盖广泛话题。",
        detailedDescription: "The Joe Rogan Experience features long-form, in-depth conversations with a wide variety of guests including scientists, authors, athletes, comedians, and thought leaders. These unfiltered discussions cover topics ranging from science and philosophy to current events and personal stories.",
        detailedDescriptionZh: "《Joe Rogan体验》以深入的长对话为特色，邀请来自各行各业的嘉宾，包括科学家、作家、运动员、喜剧演员和思想领袖。这些未经剪辑的讨论涵盖从科学、哲学到时事和个人故事的广泛话题。",
        youtubeLink: "https://www.youtube.com/@joerogan",
        youtubeLinkName: "Visit on YouTube",
        youtubeLinkNameZh: "在 YouTube 上访问",
        alternateLink: "",
        alternateLinkName: "Apple Podcasts",
        alternateLinkNameZh: "Apple Podcasts",
        image: "public/Joe Rogan.jpg",
        emoji: "🎙️"
    },
    {
        id: 15,
        name: "Philosophize This",
        level: "Upper-Intermediate",
        levelZh: "中上级",
        category: "Podcasts",
        categoryZh: "播客",
        type: "listening",
        tags: ["Philosophy", "Education", "History"],
        tagsZh: ["哲学", "教育", "历史"],
        shortDescription: "Accessible philosophy podcast exploring major thinkers and ideas.",
        shortDescriptionZh: "通俗易懂的哲学播客，探索重要思想家和哲学理念。",
        detailedDescription: "Philosophize This makes philosophy accessible to everyone by breaking down complex philosophical concepts and the ideas of major thinkers throughout history. The podcast presents philosophical ideas in a clear, engaging way that helps listeners understand and apply these concepts to their own lives.",
        detailedDescriptionZh: "《Philosophize This》通过解析复杂的哲学概念和历史重要思想家的理念，让哲学变得通俗易懂。该播客以清晰、引人入胜的方式呈现哲学思想，帮助听众理解并将这些概念应用到自己的生活中。",
        youtubeLink: "https://www.youtube.com/@philosophizethispodcast/videos",
        youtubeLinkName: "Visit on YouTube",
        youtubeLinkNameZh: "在 YouTube 上访问",
        alternateLink: "https://podcasts.apple.com/cn/podcast/philosophize-this/id659155419",
        alternateLinkName: "Visit on Apple Podcasts",
        alternateLinkNameZh: "在苹果播客上访问",
        image: "public/Philosophize this.png",
        emoji: "🤔"
    },
    {
        id: 16,
        name: "Hidden Brain",
        level: "Upper-Intermediate",
        levelZh: "中上级",
        category: "Podcasts",
        categoryZh: "播客",
        type: "listening",
        tags: ["Psychology", "Science", "Behavior"],
        tagsZh: ["心理学", "科学", "行为"],
        shortDescription: "Science-based podcast exploring human behavior and the mind.",
        shortDescriptionZh: "基于科学的播客，探索人类行为和心理。",
        detailedDescription: "Hidden Brain uses science and storytelling to reveal the unconscious patterns that drive human behavior, shape our choices, and direct our relationships. Host Shankar Vedantam explores the hidden forces that influence our thoughts, feelings, and actions.",
        detailedDescriptionZh: "《Hidden Brain》运用科学和故事叙述，揭示驱动人类行为、塑造我们选择并指导我们关系的无意识模式。主持人Shankar Vedantam探索影响我们思想、情感和行为的隐藏力量。",
        youtubeLink: "https://www.hiddenbrain.org/",
        youtubeLinkName: "Visit on Official Website",
        youtubeLinkNameZh: "在官方网站上访问",
        alternateLink: "https://podcasts.apple.com/cn/podcast/hidden-brain/id1028908750",
        alternateLinkName: "Visit on Apple Podcasts",
        alternateLinkNameZh: "在苹果播客上访问",
        image: "public/hiddenbrain.png",
        emoji: "🧠"
    },
    {
        id: 17,
        name: "No Stupid Questions",
        level: "Upper-Intermediate",
        levelZh: "中上级",
        category: "Podcasts",
        categoryZh: "播客",
        type: "listening",
        tags: ["Psychology", "Social Science", "Conversation"],
        tagsZh: ["心理学", "社会科学", "对话"],
        shortDescription: "Thoughtful conversations exploring life's big and small questions.",
        shortDescriptionZh: "深入探讨生活中大小问题的对话。",
        detailedDescription: "No Stupid Questions features Stephen Dubner and Angela Duckworth exploring the fascinating questions that help us understand how the world works and how we can live better lives. Each episode tackles questions about human behavior, decision-making, and the science behind everyday life.",
        detailedDescriptionZh: "《No Stupid Questions》由Stephen Dubner和Angela Duckworth主持，探索帮助我们理解世界运作方式以及如何更好生活的有趣问题。每集探讨关于人类行为、决策制定和日常生活背后的科学。",
        youtubeLink: "https://freakonomics.com/series/nsq/",
        youtubeLinkName: "Visit Website",
        youtubeLinkNameZh: "访问网站",
        alternateLink: "https://podcasts.apple.com/cn/podcast/no-stupid-questions/id1510056899",
        alternateLinkName: "Visit on Apple Podcasts",
        alternateLinkNameZh: "在苹果播客上访问",
        image: "public/No Stupid Questions.jpg",
        emoji: "🤔"
    },
    {
        id: 18,
        name: "Aeon",
        level: "Upper-Intermediate",
        levelZh: "中上级",
        category: "Articles",
        categoryZh: "文章",
        type: "reading",
        tags: ["Philosophy", "Science", "Culture"],
        tagsZh: ["哲学", "科学", "文化"],
        shortDescription: "Long-form essays on philosophy, science, and culture.",
        shortDescriptionZh: "关于哲学、科学和文化的深度长文。",
        detailedDescription: "Aeon publishes long-form essays and articles on philosophy, science, psychology, society, and culture. The platform features thoughtful, well-researched pieces that explore complex ideas and current issues in depth, making it ideal for advanced readers seeking intellectual engagement.",
        detailedDescriptionZh: "Aeon发表关于哲学、科学、心理学、社会和文化的长篇散文和文章。该平台提供经过深思熟虑、研究充分的文章，深入探索复杂思想和当前问题，非常适合寻求智力参与的高级读者。",
        youtubeLink: "https://aeon.co/essays",
        youtubeLinkName: "Visit Website",
        youtubeLinkNameZh: "访问网站",
        alternateLink: "",
        alternateLinkName: "Apple Podcasts",
        alternateLinkNameZh: "Apple Podcasts",
        image: "public/aeon.png",
        emoji: "📝"
    },
    {
        id: 19,
        name: "The Conversation",
        level: "Upper-Intermediate",
        levelZh: "中上级",
        category: "Articles",
        categoryZh: "文章",
        type: "reading",
        tags: ["News", "Science", "Analysis"],
        tagsZh: ["新闻", "科学", "分析"],
        shortDescription: "Academic experts writing accessible articles on current events.",
        shortDescriptionZh: "学术专家撰写的关于时事的通俗易懂文章。",
        detailedDescription: "The Conversation features articles written by academic experts in accessible language, covering current events, science, politics, culture, and more. The platform bridges the gap between academic research and public understanding, providing well-informed perspectives on important issues.",
        detailedDescriptionZh: "《The Conversation》刊登由学术专家以通俗易懂的语言撰写的文章，涵盖时事、科学、政治、文化等。该平台弥合了学术研究与公众理解之间的差距，为重要问题提供有见地的观点。",
        youtubeLink: "https://theconversation.com/global",
        youtubeLinkName: "Visit Website",
        youtubeLinkNameZh: "访问网站",
        alternateLink: "",
        alternateLinkName: "Apple Podcasts",
        alternateLinkNameZh: "Apple Podcasts",
        image: "public/The Conversation.png",
        emoji: "💬"
    },
    {
        id: 20,
        name: "Smithsonian Magazine",
        level: "Upper-Intermediate",
        levelZh: "中上级",
        category: "Articles",
        categoryZh: "文章",
        type: "reading",
        tags: ["History", "Science", "Culture"],
        tagsZh: ["历史", "科学", "文化"],
        shortDescription: "In-depth articles on history, science, arts, and culture.",
        shortDescriptionZh: "关于历史、科学、艺术和文化的深度文章。",
        detailedDescription: "Smithsonian Magazine publishes engaging articles on history, science, arts, culture, and travel. The magazine features well-researched, beautifully written pieces that explore fascinating topics from around the world, making it an excellent resource for advanced readers interested in diverse subjects.",
        detailedDescriptionZh: "《Smithsonian Magazine》发表关于历史、科学、艺术、文化和旅行的引人入胜的文章。该杂志提供经过充分研究、文笔优美的文章，探索来自世界各地的迷人话题，是感兴趣于多样主题的高级读者的绝佳资源。",
        youtubeLink: "https://www.smithsonianmag.com/",
        youtubeLinkName: "Visit Website",
        youtubeLinkNameZh: "访问网站",
        alternateLink: "",
        alternateLinkName: "Apple Podcasts",
        alternateLinkNameZh: "Apple Podcasts",
        image: "public/Smithsonian Magazine.jpg",
        emoji: "🏛️"
    },
    {
        id: 21,
        name: "Knowable Magazine",
        level: "Upper-Intermediate",
        levelZh: "中上级",
        category: "Articles",
        categoryZh: "文章",
        type: "reading",
        tags: ["Science", "Research", "Education"],
        tagsZh: ["科学", "研究", "教育"],
        shortDescription: "Science journalism making research accessible to everyone.",
        shortDescriptionZh: "让科学研究变得通俗易懂的科学新闻。",
        detailedDescription: "Knowable Magazine translates complex scientific research into engaging, accessible articles. The publication covers a wide range of scientific topics, from psychology and neuroscience to climate science and technology, helping readers understand the latest discoveries and their implications.",
        detailedDescriptionZh: "《Knowable Magazine》将复杂的科学研究转化为引人入胜、通俗易懂的文章。该出版物涵盖广泛的科学主题，从心理学和神经科学到气候科学和技术，帮助读者了解最新发现及其影响。",
        youtubeLink: "https://knowablemagazine.org/",
        youtubeLinkName: "Visit Website",
        youtubeLinkNameZh: "访问网站",
        alternateLink: "",
        alternateLinkName: "Apple Podcasts",
        alternateLinkNameZh: "Apple Podcasts",
        image: "public/Knowlable Magazine.png",
        emoji: "🔬"
    },
    {
        id: 22,
        name: "Crime Junkie",
        level: "Upper-Intermediate",
        levelZh: "中上级",
        category: "Videos/Podcasts",
        categoryZh: "视频/播客",
        type: "listening",
        tags: ["True Crime", "Mystery", "Storytelling"],
        tagsZh: ["真实犯罪", "悬疑", "故事叙述"],
        shortDescription: "True crime podcast telling compelling stories of solved and unsolved cases.",
        shortDescriptionZh: "讲述已解决和未解决案件的真实犯罪播客。",
        detailedDescription: "Crime Junkie is a weekly true crime podcast that tells compelling stories of solved and unsolved crimes. Hosts Ashley Flowers and Brit Prawat present well-researched cases in an engaging narrative style, making it popular among true crime enthusiasts.",
        detailedDescriptionZh: "《Crime Junkie》是一个每周更新的真实犯罪播客，讲述已解决和未解决犯罪的引人入胜故事。主持人Ashley Flowers和Brit Prawat以引人入胜的叙述风格呈现经过充分研究的案件，在真实犯罪爱好者中很受欢迎。",
        youtubeLink: "https://www.youtube.com/@CrimeJunkie/videos",
        youtubeLinkName: "Visit on YouTube",
        youtubeLinkNameZh: "在 YouTube 上访问",
        alternateLink: "https://podcasts.apple.com/cn/podcast/crime-junkie/id1322200189",
        alternateLinkName: "Visit on Apple Podcasts",
        alternateLinkNameZh: "在苹果播客上访问",
        image: "public/Crime Junkie.jpg",
        emoji: "🔍"
    },
    {
        id: 23,
        name: "30 Morbid Minutes",
        level: "Upper-Intermediate",
        levelZh: "中上级",
        category: "Podcasts",
        categoryZh: "播客",
        type: "listening",
        tags: ["True Crime", "Mystery", "Dark History"],
        tagsZh: ["真实犯罪", "悬疑", "黑暗历史"],
        shortDescription: "True crime podcast exploring dark and mysterious cases.",
        shortDescriptionZh: "探索黑暗和神秘案件的真实犯罪播客。",
        detailedDescription: "30 Morbid Minutes delves into true crime cases, mysteries, and dark historical events. The podcast presents well-researched stories in a compelling narrative format, exploring the darker side of human nature and history.",
        detailedDescriptionZh: "《30 Morbid Minutes》深入探讨真实犯罪案件、悬疑事件和黑暗历史事件。该播客以引人入胜的叙述形式呈现经过充分研究的故事，探索人性和历史的黑暗面。",
        youtubeLink: "https://podcasts.apple.com/cn/podcast/30-morbid-minutes/id1615076880",
        youtubeLinkName: "Visit on Apple Podcasts",
        youtubeLinkNameZh: "在苹果播客上访问",
        alternateLink: "",
        alternateLinkName: "Apple Podcasts",
        alternateLinkNameZh: "Apple Podcasts",
        image: "public/30 Morbid Minutes.jpg",
        emoji: "⚰️"
    },
    {
        id: 24,
        name: "Sounds Like a Cult",
        level: "Upper-Intermediate",
        levelZh: "中上级",
        category: "Videos/Podcasts",
        categoryZh: "视频/播客",
        type: "listening",
        tags: ["Culture", "Social Commentary", "Analysis"],
        tagsZh: ["文化", "社会评论", "分析"],
        shortDescription: "Podcast examining modern culture and cult-like behaviors.",
        shortDescriptionZh: "审视现代文化和类邪教行为的播客。",
        detailedDescription: "Sounds Like a Cult explores modern culture and examines various groups, trends, and institutions through the lens of cult-like behavior. Host Amanda Montell uses humor and analysis to investigate everything from wellness culture to fandoms, making listeners think critically about the world around them.",
        detailedDescriptionZh: "《Sounds Like a Cult》探索现代文化，通过类邪教行为的视角审视各种群体、趋势和机构。主持人Amanda Montell运用幽默和分析，从健康文化到粉丝群体，让听众批判性地思考周围的世界。",
        youtubeLink: "https://www.youtube.com/@AmandaMontellPodcasts/videos",
        youtubeLinkName: "Visit on YouTube",
        youtubeLinkNameZh: "在 YouTube 上访问",
        alternateLink: "https://podcasts.apple.com/cn/podcast/sounds-like-a-cult/id1566917047",
        alternateLinkName: "Visit on Apple Podcasts",
        alternateLinkNameZh: "在苹果播客上访问",
        image: "public/Sounds like a cult.jpg",
        emoji: "🎭"
    },
    {
        id: 25,
        name: "Women at Work",
        level: "Upper-Intermediate",
        levelZh: "中上级",
        category: "Podcasts",
        categoryZh: "播客",
        type: "listening",
        tags: ["Career", "Women", "Professional Development"],
        tagsZh: ["职业", "女性", "职业发展"],
        shortDescription: "Podcast exploring women's experiences in the workplace.",
        shortDescriptionZh: "探讨女性职场经历的播客。",
        detailedDescription: "Women at Work features conversations about the challenges and opportunities women face in their careers. The podcast covers topics such as negotiation, leadership, work-life balance, and navigating workplace dynamics, providing practical advice and insights for professional women.",
        detailedDescriptionZh: "《Women at Work》探讨女性在职业生涯中面临的挑战和机遇。该播客涵盖谈判、领导力、工作与生活平衡以及应对职场动态等话题，为职业女性提供实用建议和见解。",
        youtubeLink: "https://podcasts.apple.com/cn/podcast/women-at-work/id1336174427",
        youtubeLinkName: "Visit on Apple Podcasts",
        youtubeLinkNameZh: "在苹果播客上访问",
        alternateLink: "",
        alternateLinkName: "Apple Podcasts",
        alternateLinkNameZh: "Apple Podcasts",
        image: "public/Woman at work.avif",
        emoji: "💼"
    },
    {
        id: 26,
        name: "Modern Love",
        level: "Upper-Intermediate",
        levelZh: "中上级",
        category: "Videos/Podcasts",
        categoryZh: "视频/播客",
        type: "listening",
        tags: ["Relationships", "Stories", "Emotional"],
        tagsZh: ["人际关系", "故事", "情感"],
        shortDescription: "Stories about love, loss, and redemption from The New York Times.",
        shortDescriptionZh: "来自《纽约时报》的关于爱、失去和救赎的故事。",
        detailedDescription: "Modern Love features personal essays about love, relationships, and human connections, originally published in The New York Times. The podcast brings these stories to life through narration, exploring the complexities of love in all its forms.",
        detailedDescriptionZh: "《Modern Love》收录最初发表在《纽约时报》上的关于爱情、人际关系和人类联系的个人散文。该播客通过叙述让这些故事栩栩如生，探索各种形式的爱情的复杂性。",
        youtubeLink: "https://www.youtube.com/playlist?list=PLdMrbgYfVl-s2_KrR5DosEB0gqr4w-XZd",
        youtubeLinkName: "Visit on YouTube",
        youtubeLinkNameZh: "在 YouTube 上访问",
        alternateLink: "https://podcasts.apple.com/cn/podcast/modern-love/id1065559535",
        alternateLinkName: "Visit on Apple Podcasts",
        alternateLinkNameZh: "在苹果播客上访问",
        image: "public/Modern Love.png",
        emoji: "💕"
    },
    {
        id: 27,
        name: "Luke's ENGLISH Podcast",
        level: "Intermediate",
        levelZh: "中级",
        category: "Videos/Podcasts",
        categoryZh: "视频/播客",
        type: "listening",
        tags: ["English Learning", "British English", "Education"],
        tagsZh: ["英语学习", "英式英语", "教育"],
        shortDescription: "Comprehensive English learning podcast with British English focus.",
        shortDescriptionZh: "专注于英式英语的综合英语学习播客。",
        detailedDescription: "Luke's ENGLISH Podcast offers comprehensive English lessons covering vocabulary, grammar, pronunciation, and British culture. Host Luke Thompson provides engaging content that helps advanced learners improve their English skills while learning about British English and culture.",
        detailedDescriptionZh: "《Luke's ENGLISH Podcast》提供涵盖词汇、语法、发音和英国文化的综合英语课程。主持人Luke Thompson提供引人入胜的内容，帮助高级学习者在学习英式英语和文化的同时提高英语技能。",
        youtubeLink: "https://www.youtube.com/@LukesEnglishPodcast",
        youtubeLinkName: "Visit on YouTube",
        youtubeLinkNameZh: "在 YouTube 上访问",
        alternateLink: "https://podcasts.apple.com/cn/podcast/lukes-english-podcast-learn-british-english-with-luke/id312059190",
        alternateLinkName: "Visit on Apple Podcasts",
        alternateLinkNameZh: "在苹果播客上访问",
        image: "public/Luke's English Podcast.jpg",
        emoji: "🇬🇧"
    },
    {
        id: 28,
        name: "James Clear",
        level: "Intermediate",
        levelZh: "中级",
        category: "Articles",
        categoryZh: "文章",
        type: "reading",
        tags: ["Productivity", "Habits", "Personal Development"],
        tagsZh: ["生产力", "习惯", "个人发展"],
        shortDescription: "Articles on habits, decision-making, and continuous improvement.",
        shortDescriptionZh: "关于习惯、决策制定和持续改进的文章。",
        detailedDescription: "James Clear writes about habits, decision-making, and continuous improvement. His articles provide practical insights on building better systems, making better choices, and living a more productive and fulfilling life. The content is based on scientific research and real-world applications.",
        detailedDescriptionZh: "James Clear撰写关于习惯、决策制定和持续改进的文章。他的文章提供关于建立更好的系统、做出更好的选择以及过上更有生产力和充实生活的实用见解。内容基于科学研究和实际应用。",
        youtubeLink: "https://jamesclear.com/articles",
        youtubeLinkName: "Visit Website",
        youtubeLinkNameZh: "访问网站",
        alternateLink: "",
        alternateLinkName: "Apple Podcasts",
        alternateLinkNameZh: "Apple Podcasts",
        image: "public/James Clear.png",
        emoji: "💡"
    },
    {
        id: 29,
        name: "Mark Manson",
        level: "Intermediate",
        levelZh: "中级",
        category: "Articles",
        categoryZh: "文章",
        type: "reading",
        tags: ["Personal Development", "Philosophy", "Life Advice"],
        tagsZh: ["个人发展", "哲学", "人生建议"],
        shortDescription: "Honest, counterintuitive advice on life, relationships, and happiness.",
        shortDescriptionZh: "关于生活、人际关系和幸福的诚实、反直觉的建议。",
        detailedDescription: "Mark Manson writes about personal development, relationships, and life philosophy with a no-nonsense, counterintuitive approach. His articles challenge conventional wisdom and provide honest, practical advice on living a better life, making it ideal for readers seeking thought-provoking content.",
        detailedDescriptionZh: "Mark Manson以直率、反直觉的方式撰写关于个人发展、人际关系和人生哲学的文章。他的文章挑战传统智慧，为过上更好的生活提供诚实、实用的建议，非常适合寻求发人深省内容的读者。",
        youtubeLink: "https://markmanson.net/articles",
        youtubeLinkName: "Visit Website",
        youtubeLinkNameZh: "访问网站",
        alternateLink: "",
        alternateLinkName: "Apple Podcasts",
        alternateLinkNameZh: "Apple Podcasts",
        image: "public/Mark Manson.png",
        emoji: "💭"
    },
    {
        id: 30,
        name: "Lifehacker",
        level: "Intermediate",
        levelZh: "中级",
        category: "Articles",
        categoryZh: "文章",
        type: "reading",
        tags: ["Productivity", "Technology", "Tips"],
        tagsZh: ["生产力", "科技", "技巧"],
        shortDescription: "Tips and tricks for improving your life and productivity.",
        shortDescriptionZh: "改善生活和提高生产力的技巧和窍门。",
        detailedDescription: "Lifehacker provides tips, tricks, and advice for improving various aspects of your life, from productivity and technology to health and finance. The site features practical, actionable content that helps readers solve problems and work smarter.",
        detailedDescriptionZh: "Lifehacker提供改善生活各个方面的技巧、窍门和建议，从生产力和科技到健康和财务。该网站提供实用的、可操作的内容，帮助读者解决问题并更聪明地工作。",
        youtubeLink: "https://lifehacker.com/",
        youtubeLinkName: "Visit Website",
        youtubeLinkNameZh: "访问网站",
        alternateLink: "",
        alternateLinkName: "Apple Podcasts",
        alternateLinkNameZh: "Apple Podcasts",
        image: "public/LifeHacker.webp",
        emoji: "⚡"
    },
    {
        id: 31,
        name: "All Ears English Podcast",
        level: "Lower-Intermediate",
        levelZh: "中下级",
        category: "Videos/Podcasts",
        categoryZh: "视频/播客",
        type: "listening",
        tags: ["English Learning", "Conversation", "American English"],
        tagsZh: ["英语学习", "对话", "美式英语"],
        shortDescription: "English learning podcast focusing on natural American English conversation.",
        shortDescriptionZh: "专注于自然美式英语对话的英语学习播客。",
        detailedDescription: "All Ears English Podcast helps advanced learners improve their English through natural, engaging conversations. The hosts discuss real-world topics, cultural insights, and practical language tips, making it perfect for learners who want to sound more natural and confident in American English.",
        detailedDescriptionZh: "《All Ears English Podcast》通过自然、引人入胜的对话帮助高级学习者提高英语水平。主持人讨论现实世界的话题、文化见解和实用语言技巧，非常适合想要在美式英语中听起来更自然、更自信的学习者。",
        youtubeLink: "https://www.youtube.com/@AllEarsEnglishPodcast/videos",
        youtubeLinkName: "Visit on YouTube",
        youtubeLinkNameZh: "在 YouTube 上访问",
        alternateLink: "https://podcasts.apple.com/cn/podcast/all-ears-english-podcast/id751574016",
        alternateLinkName: "Visit on Apple Podcasts",
        alternateLinkNameZh: "在苹果播客上访问",
        image: "public/All Ears English.jpeg",
        emoji: "👂"
    }
];

